name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build React app
      run: |
        npm install
        npm run build

    - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag your-image-name ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
